sudo: required
language: go

go:
  - 1.12.x

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - curl -sL cli.openfaas.com | sudo sh

script:
  - faas-cli build -f certinfo.yml

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo $DOCKER_PASS | docker login -u "$DOCKER_USER" --password-stdin;
    faas-cli push -f certinfo.yml;
    fi
